{"name": "test_signup_failure[email_already_taken]", "status": "passed", "description": "测试用户注册失败", "steps": [{"name": "执行测试用例: 邮箱已被占用时注册失败", "status": "passed", "steps": [{"name": "验证错误信息", "status": "passed", "start": 1751092024198, "stop": 1751092024245}], "start": 1751092021585, "stop": 1751092024245}], "parameters": [{"name": "test_case", "value": "{'id': 'email_already_taken', 'email': 'new-user@example.com', 'password': 'password', 'password_confirmation': 'password', 'username': 'new user 1', 'rank': 'NORMAL', 'address': 'Las Vegas, Nevada', 'tel': '01234567891', 'gender': 'FEMALE', 'birthday': '2000-01-01', 'notification': True, 'expected_messages': {'email': 'Email has already been taken.', 'password': '', 'password_confirmation': '', 'username': '', 'address': '', 'tel': '', 'gender': '', 'birthday': ''}, 'description': '邮箱已被占用时注册失败'}"}], "start": 1751092021585, "stop": 1751092024245, "uuid": "c9f186dc-698b-4507-8324-9238dd3db3b2", "historyId": "99f810dbd84ea393ab8aca7e84ed9385", "testCaseId": "5a59ec60b5050f5d2e8136bb5d5a68e3", "fullName": "testcase.test_signup.TestSignup#test_signup_failure", "labels": [{"name": "story", "value": "注册失败"}, {"name": "feature", "value": "用户注册"}, {"name": "tag", "value": "order(2)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('driver')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_signup"}, {"name": "subSuite", "value": "TestSignup"}, {"name": "host", "value": "SQG"}, {"name": "thread", "value": "19816-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_signup"}]}